# Generated by Django 4.2.7 on 2023-11-16 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Task_apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='customerId',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, to='Task_apis.users'),
            preserve_default=False,
        ),
    ]
